"use client";

import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { useState } from "react";

type AppCard = {
  name: string;
  details: string;
  icon: string;
  action: string;
  filename: string;
  href: string;
};

const APPS: AppCard[] = [
  {
    name: "Windows",
    details: "Windows 10/11 (64-bit)",
    icon: "desktop_windows",
    action: "Скачать .exe",
    filename: "portal-windows.exe",
    href: "",
  },
  {
    name: "macOS",
    details: "macOS 11+, Intel / Apple Silicon",
    icon: "laptop_mac",
    action: "Скачать .dmg",
    filename: "portal-macos.dmg",
    href: "",
  },
  {
    name: "Linux",
    details: "Debian, Ubuntu, Fedora",
    icon: "terminal",
    action: "Скачать .deb",
    filename: "portal-linux.deb",
    href: "",
  },
  {
    name: "iOS",
    details: "iPhone / iPad",
    icon: "phone_iphone",
    action: "Открыть App Store",
    filename: "",
    href: "https://apps.apple.com",
  },
  {
    name: "Android",
    details: "Android 8+",
    icon: "android",
    action: "Открыть Google Play",
    filename: "",
    href: "https://play.google.com",
  },
];

function triggerFakeDownload(fileName: string): void {
  const blob = new Blob([`Mock build package: ${fileName}\nGenerated by portal-next demo.`], {
    type: "text/plain;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

export default function DownloadsPage() {
  const [toast, setToast] = useState<string | null>(null);

  const notify = (message: string): void => {
    setToast(message);
    window.setTimeout(() => setToast(null), 1800);
  };

  const onAction = (name: string, fileName: string, href: string): void => {
    if (fileName) {
      triggerFakeDownload(fileName);
      notify(`${name}: загрузка началась.`);
      return;
    }

    if (href) {
      window.open(href, "_blank", "noopener,noreferrer");
      notify(`${name}: открыли магазин приложений.`);
      return;
    }

    notify(`${name}: ссылка будет добавлена в следующем обновлении.`);
  };

  return (
    <main className="space-y-6">
      <section className="glass-card p-7">
        <div className="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
          <div>
            <p className="font-mono text-xs uppercase tracking-[0.18em] text-slate-500">download center</p>
            <h1 className="mt-2 font-display text-4xl font-bold">Скачать приложение PORTAL</h1>
            <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">
              Выберите платформу и подключитесь за пару минут: без сложной настройки и лишних шагов.
            </p>
          </div>
          <Link href="/dashboard" className="outline-btn rounded-xl px-5 py-2.5 text-sm font-semibold uppercase tracking-[0.12em]">
            Открыть кабинет
          </Link>
        </div>
      </section>

      <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        {APPS.map((app, idx) => (
          <motion.article
            key={app.name}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.05 }}
            className="glass-card p-6"
          >
            <span className="float-slow material-symbols-rounded rounded-xl bg-violet-100 p-3 text-3xl text-violet-600 dark:bg-violet-900/35 dark:text-violet-200">
              {app.icon}
            </span>
            <h2 className="mt-4 font-display text-3xl font-semibold">{app.name}</h2>
            <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{app.details}</p>
            <button
              type="button"
              onClick={() => onAction(app.name, app.filename, app.href)}
              className="btn-primary mt-6 w-full rounded-xl py-2.5 text-sm font-semibold uppercase tracking-[0.12em]"
            >
              {app.action}
            </button>
          </motion.article>
        ))}
      </section>

      <section className="glass-card p-7">
        <div className="flex flex-col items-start justify-between gap-5 md:flex-row md:items-center">
          <div>
            <h3 className="font-display text-2xl font-semibold">Быстрый запуск через Telegram</h3>
            <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">
              Шаг 1: откройте бота. Шаг 2: получите ключ. Шаг 3: вставьте в приложение и подключитесь.
            </p>
            <p className="mt-1 text-xs text-slate-500">Если что-то не сработало с первого раза, поддержка поможет в чате за 10-15 минут.</p>
          </div>
          <a
            href="https://t.me/portal_vpn"
            target="_blank"
            rel="noreferrer"
            className="btn-primary rounded-xl px-6 py-3 text-sm font-semibold uppercase tracking-[0.12em]"
          >
            Перейти в бот
          </a>
        </div>
      </section>

      <AnimatePresence>
        {toast ? (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 12 }}
            className="fixed bottom-24 left-1/2 z-[210] -translate-x-1/2 rounded-full bg-slate-900 px-4 py-2 text-xs text-white shadow-xl"
          >
            {toast}
          </motion.div>
        ) : null}
      </AnimatePresence>
    </main>
  );
}
