import re
import sys
import unittest
from pathlib import Path

from sqlalchemy import Identity, JSON
from sqlalchemy.dialects import postgresql, sqlite
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.schema import CreateTable


RU_PROBE_POSTGRES_TABLES = {
    "ru_probe_runs": {
        "columns": {
            "id": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "run_id": "VARCHAR(36) NOT NULL",
            "schema_version": "INTEGER NOT NULL",
            "origin": "VARCHAR(16) NOT NULL",
            "probe_host_id": "VARCHAR(64) NOT NULL",
            "probe_host_label": "VARCHAR(128) NOT NULL",
            "probe_public_ip": "VARCHAR(64)",
            "runner_version": "VARCHAR(64) NOT NULL",
            "started_at": "TIMESTAMPTZ NOT NULL",
            "finished_at": "TIMESTAMPTZ NOT NULL",
            "received_at": "TIMESTAMPTZ NOT NULL",
            "manifest_revision": "VARCHAR(64) NOT NULL",
            "execution_status": "VARCHAR(32) NOT NULL",
            "evidence_code": "VARCHAR(64)",
            "environment_verdict": "VARCHAR(32) NOT NULL",
            "release_verdict": "VARCHAR(32) NOT NULL",
            "current_eligible": "BOOLEAN NOT NULL DEFAULT FALSE",
            "ineligible_reason": "VARCHAR(64)",
            "google_reachable": "BOOLEAN",
            "xhttp_alive": "BOOLEAN",
            "hysteria_alive": "BOOLEAN",
            "server_reason": "VARCHAR(500)",
            "server_summary": "VARCHAR(1000)",
            "artifact_sha256": "VARCHAR(64) NOT NULL",
            "ingest_key_id": "VARCHAR(128) NOT NULL",
            "retention_hold": "BOOLEAN NOT NULL DEFAULT FALSE",
            "retention_hold_reason": "VARCHAR(500)",
            "retention_held_at": "TIMESTAMPTZ",
        },
        "constraints": {
            "uq_ru_probe_runs_run_id": "UNIQUE (run_id)",
        },
    },
    "ru_probe_target_results": {
        "columns": {
            "id": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "run_db_id": "INTEGER NOT NULL",
            "target_id": "VARCHAR(128) NOT NULL",
            "target_kind": "VARCHAR(32) NOT NULL",
            "scope": "VARCHAR(32) NOT NULL",
            "node_code": "VARCHAR(32)",
            "endpoint_fingerprint": "VARCHAR(64) NOT NULL",
            "endpoint_host": "VARCHAR(255) NOT NULL",
            "endpoint_port": "INTEGER NOT NULL",
            "endpoint_sni": "VARCHAR(255)",
            "requested_address_families_json": "JSONB NOT NULL",
            "transport_metadata_json": "JSONB NOT NULL",
            "transport_profile": "VARCHAR(64) NOT NULL",
            "probe_mode": "VARCHAR(64) NOT NULL",
            "http_path": "VARCHAR(512)",
            "min_body_bytes": "INTEGER",
            "local_probe_profile_id": "VARCHAR(128)",
            "observed_at": "TIMESTAMPTZ NOT NULL",
            "overall_status": "VARCHAR(32) NOT NULL",
            "current_eligible": "BOOLEAN NOT NULL DEFAULT FALSE",
            "ineligible_reason": "VARCHAR(64)",
            "dns_status": "VARCHAR(32) NOT NULL",
            "dns_latency_ms": "INTEGER",
            "tcp_status": "VARCHAR(32) NOT NULL",
            "tcp_latency_ms": "INTEGER",
            "tls_status": "VARCHAR(32) NOT NULL",
            "tls_latency_ms": "INTEGER",
            "http_large_body_status": "VARCHAR(32) NOT NULL",
            "http_large_body_latency_ms": "INTEGER",
            "transport_handshake_status": "VARCHAR(32) NOT NULL",
            "transport_handshake_latency_ms": "INTEGER",
            "ipv4_status": "VARCHAR(32) NOT NULL",
            "ipv6_status": "VARCHAR(32) NOT NULL",
            "reported_transport_handshake_status": "VARCHAR(32) NOT NULL",
            "reported_transport_classification": "VARCHAR(64) NOT NULL",
            "server_reason_code": "VARCHAR(64)",
            "server_detail": "VARCHAR(500)",
        },
        "constraints": {
            "fk_ru_probe_target_results_run": (
                "FOREIGN KEY (run_db_id) REFERENCES ru_probe_runs(id) "
                "ON DELETE CASCADE"
            ),
            "uq_ru_probe_target_run_target": "UNIQUE (run_db_id, target_id)",
        },
    },
    "ru_probe_uploader_heartbeats": {
        "columns": {
            "id": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "probe_host_id": "VARCHAR(64) NOT NULL",
            "observed_at": "TIMESTAMPTZ NOT NULL",
            "received_at": "TIMESTAMPTZ NOT NULL",
            "service_version": "VARCHAR(64) NOT NULL",
            "pending_count": "INTEGER NOT NULL DEFAULT 0",
            "blocked_count": "INTEGER NOT NULL DEFAULT 0",
            "quarantine_count": "INTEGER NOT NULL DEFAULT 0",
            "oldest_pending_at": "TIMESTAMPTZ",
            "archive_write_ok": "BOOLEAN NOT NULL DEFAULT FALSE",
            "disk_free_bytes": "BIGINT",
            "disk_state": "VARCHAR(32) NOT NULL",
            "last_error_code": "VARCHAR(64)",
            "ingest_key_id": "VARCHAR(128) NOT NULL",
        },
        "constraints": {
            "uq_ru_probe_uploader_heartbeat_host_observed": (
                "UNIQUE (probe_host_id, observed_at)"
            ),
        },
    },
    "internal_ingest_nonces": {
        "columns": {
            "id": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "key_scope": "VARCHAR(64) NOT NULL",
            "key_id": "VARCHAR(128) NOT NULL",
            "nonce_hash": "VARCHAR(64) NOT NULL",
            "request_path": "VARCHAR(512) NOT NULL",
            "request_timestamp": "TIMESTAMPTZ NOT NULL",
            "body_sha256": "VARCHAR(64) NOT NULL",
            "expires_at": "TIMESTAMPTZ NOT NULL",
            "created_at": "TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP",
        },
        "constraints": {
            "uq_internal_ingest_nonce_scope_key_hash": (
                "UNIQUE (key_scope, key_id, nonce_hash)"
            ),
        },
    },
}

RU_PROBE_POSTGRES_INDEXES = {
    "ix_ru_probe_runs_finished_at": ("ru_probe_runs", "finished_at"),
    "ix_ru_probe_runs_release_verdict": ("ru_probe_runs", "release_verdict"),
    "ix_ru_probe_runs_current_eligible": ("ru_probe_runs", "current_eligible"),
    "ix_ru_probe_runs_probe_host_label": ("ru_probe_runs", "probe_host_label"),
    "ix_ru_probe_target_results_node_code": (
        "ru_probe_target_results",
        "node_code",
    ),
    "ix_ru_probe_target_results_target_kind": (
        "ru_probe_target_results",
        "target_kind",
    ),
    "ix_ru_probe_target_results_overall_status": (
        "ru_probe_target_results",
        "overall_status",
    ),
    "ix_ru_probe_target_results_node_observed_at": (
        "ru_probe_target_results",
        "node_code, observed_at DESC",
    ),
    "ix_ru_probe_target_results_run_node": (
        "ru_probe_target_results",
        "run_db_id, node_code",
    ),
    "ix_ru_probe_uploader_heartbeats_received_at": (
        "ru_probe_uploader_heartbeats",
        "received_at",
    ),
    "ix_ru_probe_uploader_heartbeats_probe_host_id": (
        "ru_probe_uploader_heartbeats",
        "probe_host_id",
    ),
    "ix_ru_probe_uploader_heartbeats_host_observed_at": (
        "ru_probe_uploader_heartbeats",
        "probe_host_id, observed_at DESC",
    ),
    "ix_internal_ingest_nonces_expires_at": (
        "internal_ingest_nonces",
        "expires_at",
    ),
}


def _normalize_sql(value: str) -> str:
    return " ".join(str(value).split())


def _split_top_level_csv(value: str) -> list[str]:
    parts: list[str] = []
    depth = 0
    start = 0
    for index, char in enumerate(value):
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append(value[start:index].strip())
            start = index + 1
    parts.append(value[start:].strip())
    return parts


def _postgres_table_contract(sql: str, table_name: str) -> dict:
    normalized = _normalize_sql(sql)
    prefix = f"CREATE TABLE IF NOT EXISTS {table_name} ("
    if not normalized.startswith(prefix) or not normalized.endswith(");"):
        raise AssertionError(f"Unexpected CREATE TABLE shape for {table_name}: {sql}")
    body = normalized[len(prefix) : -2].strip()
    columns: dict[str, str] = {}
    constraints: dict[str, str] = {}
    for item in _split_top_level_csv(body):
        if item.startswith("CONSTRAINT "):
            _keyword, name, definition = item.split(" ", 2)
            constraints[name] = definition
            continue
        name, definition = item.split(" ", 1)
        columns[name] = definition
    return {"columns": columns, "constraints": constraints}


def _postgres_index_contract(sql_statements: list[str]) -> dict:
    result = {}
    pattern = re.compile(
        r"CREATE INDEX IF NOT EXISTS ([A-Za-z0-9_]+) "
        r"ON ([A-Za-z0-9_]+)\s*\((.+)\);"
    )
    for statement in sql_statements:
        match = pattern.fullmatch(_normalize_sql(statement))
        if not match or match.group(2) not in RU_PROBE_POSTGRES_TABLES:
            continue
        result[match.group(1)] = (match.group(2), match.group(3))
    return result


class _ScalarResult:
    def __init__(self, value):
        self._value = value

    def scalar(self):
        return self._value

    def fetchall(self):
        return []

    def fetchone(self):
        return None


class _FakeConn:
    def __init__(self, *, existing_columns=None, varchar_limits=None):
        self.existing_columns = set(existing_columns or [])
        self.varchar_limits = dict(varchar_limits or {})
        self.executed = []

    def execute(self, statement, params=None):
        sql = str(statement)
        self.executed.append((sql, dict(params or {})))
        if "information_schema.columns" in sql and "SELECT EXISTS" in sql:
            key = (params or {}).get("table_name"), (params or {}).get("column_name")
            return _ScalarResult(key in self.existing_columns)
        if "character_maximum_length" in sql:
            key = (params or {}).get("table_name"), (params or {}).get("column_name")
            return _ScalarResult(self.varchar_limits.get(key))
        return _ScalarResult(None)


class _BeginContext:
    def __init__(self, conn):
        self.conn = conn

    def __enter__(self):
        return self.conn

    def __exit__(self, exc_type, exc, traceback):
        return False


class _FakeEngine:
    def __init__(self):
        self.conn = _FakeConn()

    def begin(self):
        return _BeginContext(self.conn)


class PostgresMigrationHelperTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        portal_dir = Path(__file__).resolve().parents[1] / "portal_bot"
        if str(portal_dir) not in sys.path:
            sys.path.insert(0, str(portal_dir))
        import migrations
        import models

        cls.migrations = migrations
        cls.models = models

    def test_existing_column_skips_noop_alter(self) -> None:
        conn = _FakeConn(existing_columns={("users", "referral_code")})

        changed = self.migrations._postgres_add_column_if_missing(conn, "users", "referral_code", "VARCHAR(10)")

        self.assertFalse(changed)
        self.assertEqual(len(conn.executed), 1)
        self.assertNotIn("ALTER TABLE", conn.executed[0][0])

    def test_missing_column_runs_alter_once(self) -> None:
        conn = _FakeConn()

        changed = self.migrations._postgres_add_column_if_missing(conn, "users", "referral_code", "VARCHAR(10)")

        self.assertTrue(changed)
        alter_sql = conn.executed[-1][0]
        self.assertIn("ALTER TABLE users ADD COLUMN referral_code VARCHAR(10)", alter_sql)

    def test_unsafe_identifier_is_rejected(self) -> None:
        conn = _FakeConn()

        with self.assertRaises(ValueError):
            self.migrations._postgres_add_column_if_missing(conn, "users; drop table users", "referral_code", "TEXT")

    def test_varchar_limit_reads_information_schema(self) -> None:
        conn = _FakeConn(varchar_limits={("gift_cards", "code"): 16})

        limit = self.migrations._postgres_varchar_limit(conn, "gift_cards", "code")

        self.assertEqual(limit, 16)

    def test_capacity_policy_backfill_sets_not_null_defaults(self) -> None:
        conn = _FakeConn()

        self.migrations._ensure_capacity_domain_postgres(conn)

        backfill_sql = next(
            sql
            for sql, _params in conn.executed
            if "INSERT INTO node_capacity_policy" in sql
        )
        for column in (
            "soft_tx_ratio",
            "drain_tx_ratio",
            "hard_tx_ratio",
            "soft_cpu_percent",
            "hard_cpu_percent",
            "stale_after_seconds",
            "max_packet_loss_percent",
            "max_tcp_retrans_percent",
            "rank_weight",
            "is_enabled",
        ):
            self.assertIn(column, backfill_sql)
        for value in ("0.70", "0.82", "0.92", "75", "90", "180", "2", "5", "100"):
            self.assertIn(value, backfill_sql)

    def test_node_pool_membership_backfill_sets_enabled_default(self) -> None:
        conn = _FakeConn()

        self.migrations._ensure_capacity_domain_postgres(conn)

        backfill_sql = next(
            sql
            for sql, _params in conn.executed
            if "INSERT INTO node_pool_membership" in sql
        )
        self.assertIn("is_enabled", backfill_sql)
        self.assertIn("TRUE", backfill_sql)

    def test_ru_probe_postgres_ddl_matches_full_contract(self) -> None:
        conn = _FakeConn()

        self.migrations._ensure_ru_probe_domain_postgres(conn)

        sql = [" ".join(statement.split()) for statement, _params in conn.executed]
        table_positions = {}
        actual_tables = {}
        for table_name in RU_PROBE_POSTGRES_TABLES:
            table_positions[table_name] = next(
                index
                for index, item in enumerate(sql)
                if item.startswith(f"CREATE TABLE IF NOT EXISTS {table_name} ")
            )
            actual_tables[table_name] = _postgres_table_contract(
                sql[table_positions[table_name]],
                table_name,
            )

        self.assertEqual(actual_tables, RU_PROBE_POSTGRES_TABLES)
        self.assertLess(
            table_positions["ru_probe_runs"],
            table_positions["ru_probe_target_results"],
        )
        self.assertLess(
            table_positions["ru_probe_target_results"],
            table_positions["ru_probe_uploader_heartbeats"],
        )
        self.assertLess(
            table_positions["ru_probe_uploader_heartbeats"],
            table_positions["internal_ingest_nonces"],
        )
        first_index_pos = next(
            index
            for index, item in enumerate(sql)
            if item.startswith("CREATE INDEX IF NOT EXISTS")
        )
        self.assertLess(
            table_positions["internal_ingest_nonces"],
            first_index_pos,
        )

        target_columns = actual_tables["ru_probe_target_results"]["columns"]
        self.assertIn("overall_status", target_columns)
        self.assertNotIn("verdict", target_columns)
        nonce_columns = actual_tables["internal_ingest_nonces"]["columns"]
        self.assertNotIn("nonce", nonce_columns)
        for columns in (item["columns"] for item in actual_tables.values()):
            for forbidden in (
                "raw_nonce",
                "signature",
                "secret",
                "raw_body",
                "raw_artifact",
                "provider_payload",
            ):
                self.assertNotIn(forbidden, columns)

    def test_ru_probe_postgres_indexes_match_full_contract(self) -> None:
        conn = _FakeConn()

        self.migrations._ensure_ru_probe_domain_postgres(conn)

        sql = [statement for statement, _params in conn.executed]
        self.assertEqual(
            _postgres_index_contract(sql),
            RU_PROBE_POSTGRES_INDEXES,
        )

    def test_ru_probe_models_use_identity_jsonb_and_sqlite_autoincrement(self) -> None:
        postgres_dialect = postgresql.dialect()
        sqlite_dialect = sqlite.dialect()
        for table_name in RU_PROBE_POSTGRES_TABLES:
            table = self.models.Base.metadata.tables[table_name]
            self.assertIsInstance(table.c.id.identity, Identity)
            postgres_ddl = _normalize_sql(
                str(CreateTable(table).compile(dialect=postgres_dialect))
            )
            sqlite_ddl = _normalize_sql(
                str(CreateTable(table).compile(dialect=sqlite_dialect))
            )
            self.assertIn("GENERATED BY DEFAULT AS IDENTITY", postgres_ddl)
            self.assertNotIn("SERIAL", postgres_ddl)
            self.assertIn("PRIMARY KEY AUTOINCREMENT", sqlite_ddl)

        target_table = self.models.Base.metadata.tables["ru_probe_target_results"]
        for column_name in (
            "requested_address_families_json",
            "transport_metadata_json",
        ):
            column_type = target_table.c[column_name].type
            self.assertIsInstance(column_type, JSON)
            self.assertIsInstance(
                column_type.dialect_impl(postgres_dialect),
                JSONB,
            )

    def test_postgres_ru_probe_ddl_immediately_follows_admin_ops(self) -> None:
        engine = _FakeEngine()

        self.migrations._run_postgres_migrations(engine)

        sql = [
            " ".join(statement.split())
            for statement, _params in engine.conn.executed
        ]
        admin_last = next(
            i for i, item in enumerate(sql) if "ix_ops_alerts_last_seen_at" in item
        )
        ru_first = next(
            i
            for i, item in enumerate(sql)
            if "CREATE TABLE IF NOT EXISTS ru_probe_runs" in item
        )
        external_orders = next(
            i
            for i, item in enumerate(sql)
            if "CREATE TABLE IF NOT EXISTS external_orders" in item
        )
        self.assertEqual(ru_first, admin_last + 1)
        self.assertLess(ru_first, external_orders)


if __name__ == "__main__":
    unittest.main()
